apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-app-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/add-base-url: "true"
    nginx.ingress.kubernetes.io/configuration-snippet: |
        rewrite ^/delete /delete break;
        rewrite ^/update /update break;
spec:
  rules:
    - host: notes.application
      http:
        paths:
          - path: /*
            pathType: Prefix
            backend:
              service:
                name: notes-app-svc
                port:
                  number: 80
