apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notes-app-ingress
spec:
  ingressClassName: nginx-example
  rules:
    - http:
        paths:
          - backend:
              service:
                name: notes-app-svc
                port:
                  number: 80
            pathType: Prefix